name: Generate Release
on:
  push:
    branches:
      - feature/dev-83-provide-shell-one-liner-for
    tags:
      - "*.*.*"

jobs:
  generate_release:
    name: Generate release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: MCJack123/ghaction-generate-release-hashes@v1
        with:
          hash-type: sha256
          file-name: hashes.txt

      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: Asset Hashes
      #     path: hashes.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: hashes.txt
